<a href="https://colab.research.google.com/github/eeyamazaki/OO_Agua/blob/main/pending_list.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

OBJETIVO

1) Checar se tudo que saiu do NETA foi para o WFM.

2) Se os status do NETA e WFM sao divergentes.

In [59]:
import os
import pandas as pda

In [60]:
df = pd.read_csv(r'/content/drive/MyDrive/Projetos/pendinglist/pendinglist.csv', sep=';')

In [61]:
df.head()

,atualizacao,ATC,ano,cdOS,OS,TSS,dsTSS,tpObj,Fornecimento,PDE,...,dtPeriodoRefer,dtRecepcao,etapa,Papel,Sujeito,tpProcPai,dsTSE,TSE,unidAcat,unidResp
0,2023-05-08 10:15:02.890,927,2023,9111675,239111675,CRM010,IRREGULARIDADE,Fornecimento,2.353002e+11,NaN,...,2023-03-30 12:18:00,2023-03-30 12:18:00,False,NaN,NaN,NaN,NaN,NaN,DEP GESTÃO DE PROCESSO COMERCIAL,DIV CONTR DE CONSUMO NORTE
1,2023-05-08 10:15:02.890,927,2023,9095919.01,239095919,6452,SUSPEITA IRREG LIG AGUA/HIDRO FORN ATIVO,Fornecimento,2.381955e+11,NaN,...,2023-03-30 11:42:00,2023-03-30 10:47:00,False,NaN,NaN,CRM010,NaN,NaN,DIV CONTR DE CONSUMO NORTE,NaN
2,2023-05-08 10:15:02.890,927,2023,9092075.01,239092075,6452,SUSPEITA IRREG LIG AGUA/HIDRO FORN ATIVO,Fornecimento,8.604052e+13,NaN,...,2023-03-30 11:33:00,2023-03-30 10:28:00,False,NaN,NaN,CRM010,NaN,NaN,DIV CONTR DE CONSUMO NORTE,NaN
3,2023-05-08 10:15:02.890,927,2023,9091992.01,239091992,6452,SUSPEITA IRREG LIG AGUA/HIDRO FORN ATIVO,Fornecimento,2.381433e+11,NaN,...,2023-03-30 11:32:00,2023-03-30 10:27:00,False,NaN,NaN,CRM010,NaN,NaN,DIV CONTR DE CONSUMO NORTE,NaN
4,2023-05-08 10:15:02.890,927,2023,9091848.01,239091848,6452,SUSPEITA IRREG LIG AGUA/HIDRO FORN ATIVO,Fornecimento,2.381445e+11,NaN,...,2023-03-30 11:30:00,2023-03-30 10:26:00,False,NaN,NaN,CRM010,IRREGULARIDADE NÃO DETECTADA,645000.0,DIV CONTR DE CONSUMO NORTE,NaN

In [62]:
df.columns

Index(['atualizacao', 'ATC', 'ano', 'cdOS', 'OS', 'TSS', 'dsTSS', 'tpObj',
       'Fornecimento', 'PDE', 'Processo', 'status', 'tpcausal', 'familia',
       'SubTipo', 'dsSubTipo', 'motivo', 'Inicitativa', 'Canal',
       'operadorResp', 'dtCriacao', 'dtPeriodoRefer', 'dtRecepcao', 'etapa',
       'Papel', 'Sujeito', 'tpProcPai', 'dsTSE', 'TSE', 'unidAcat',
       'unidResp'],
      dtype='object')

In [63]:
buscaExecucaoVM = pd.read_excel(r'/content/drive/MyDrive/Projetos/wfm/Busca_Execucao/Vila/executados-vila.xlsx')
buscaExecucaoVM.head()

/usr/local/lib/python3.10/dist-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Número OS,Etapa,Código TSS,Descrição TSS,Objeto de Origem,Iniciativa,Solicitante,Endereço,Município,Código Resultado,...,Data Início Execução,Data Fim Execução,Início Pausa,Fim Pausa,Tempo de execução efetivo,Fornecedor,Contrato,Equipe,Status da Operação,Status da OS
0,215184808,,1060,FALTA DE ÁGUA LOCAL,237635909005,INICIATIVA CLIENTE,ALESSANDRA TRONQUINI,"RUA MARIA CANDIDA, 1806, - V GUILHERME, SÃO ...",SÃO PAULO,130000,...,15/10/2021 10:20,15/10/2021 10:40,NaN,NaN,+00 00:20:00,SABESP,1.000000e+10,ALEXANDRE LUIZ BANDINI MILLER,Fechada,Fechada
1,215187959,,1110,POUCA PRESSÃO DE ÁGUA GERAL,237075261001,INICIATIVA CLIENTE,MEIRICE SOARES FIGUEIREDO,"AVENIDA CONCEICAO, 3630, - V ISOLINA, SÃO PAULO",SÃO PAULO,111000,...,15/10/2021 13:45,15/10/2021 14:07,NaN,NaN,+00 00:22:00,SABESP,1.000000e+10,GERALDO ARGOLO BITENCOURT,Fechada,Fechada
2,215202763,,2040,HIDRÔMETRO PARADO,1056565427002,INICIATIVA ADMINISTRATIVA,MANUEL DE JESUS RODRIGUES,"RUA CORONEL JORDAO, 946, C/13 - V GUILHERME, ...",SÃO PAULO,901000,...,16/10/2021 07:46,16/10/2021 07:48,NaN,NaN,+00 00:02:00,CONSORCIO NOVA NORTE VIII,4.600043e+09,HARLEY PEREIRA VILAS BOAS,Fechada,Fechada
3,215143198,,2040,HIDRÔMETRO PARADO,232061955003,INICIATIVA ADMINISTRATIVA,JOSE NILSON FERREIRA DANTAS,"RUA MOTANGUA, 95, - V IZOLINA MAZZEI, SÃO PAULO",SÃO PAULO,204000,...,15/10/2021 15:47,15/10/2021 15:55,NaN,NaN,+00 00:08:00,CONSORCIO NOVA NORTE VIII,4.600043e+09,HARLEY PEREIRA VILAS BOAS,Fechada,Fechada
4,215158085,,2040,HIDRÔMETRO PARADO,231915705004,INICIATIVA ADMINISTRATIVA,"SR. CLIENTE, ATUALIZAR CADASTRO SR. CLIE","RUA MANUEL DE ALMEIDA, 695, - V GUILHERME, S...",SÃO PAULO,204000,...,15/10/2021 15:59,15/10/2021 15:59,NaN,NaN,+00 00:00:00,CONSORCIO NOVA NORTE VIII,4.600043e+09,HARLEY PEREIRA VILAS BOAS,Fechada,Fechada

In [64]:
buscaExecucaoVM.columns

Index(['Número OS', 'Etapa', 'Código TSS', 'Descrição TSS', 'Objeto de Origem',
       'Iniciativa', 'Solicitante', 'Endereço', 'Município',
       'Código Resultado', 'Resultado', 'Nota Execução/Não Execução',
       'Tempo de Execução', 'Data de Competência', 'Data de Planejamento',
       'Data Início Execução', 'Data Fim Execução', 'Início Pausa',
       'Fim Pausa', 'Tempo de execução efetivo', 'Fornecedor', 'Contrato',
       'Equipe', 'Status da Operação', 'Status da OS'],
      dtype='object')

In [65]:
buscaExecucaoVM.columns = ['OS', 'etapa', 'TSS', 'dsTSS', 'objOrigem',
       'iniciativa', 'solicitante', 'endereco', 'municipio',
       'TSE', 'dsTSE', 'observacao',
       'tempoExecucao', 'dataCompetencia', 'dataPlanejamento',
       'dataInicioExecucao', 'dataFimExecucao', 'inicioPausa',
       'fimPausa', 'tempoExecucao', 'fornecedor', 'contrato',
       'equipe', 'statusOperacao', 'statusOS']

In [66]:
buscaExecucaoVM.head()

,OS,etapa,TSS,dsTSS,objOrigem,iniciativa,solicitante,endereco,municipio,TSE,...,dataInicioExecucao,dataFimExecucao,inicioPausa,fimPausa,tempoExecucao,fornecedor,contrato,equipe,statusOperacao,statusOS
0,215184808,,1060,FALTA DE ÁGUA LOCAL,237635909005,INICIATIVA CLIENTE,ALESSANDRA TRONQUINI,"RUA MARIA CANDIDA, 1806, - V GUILHERME, SÃO ...",SÃO PAULO,130000,...,15/10/2021 10:20,15/10/2021 10:40,NaN,NaN,+00 00:20:00,SABESP,1.000000e+10,ALEXANDRE LUIZ BANDINI MILLER,Fechada,Fechada
1,215187959,,1110,POUCA PRESSÃO DE ÁGUA GERAL,237075261001,INICIATIVA CLIENTE,MEIRICE SOARES FIGUEIREDO,"AVENIDA CONCEICAO, 3630, - V ISOLINA, SÃO PAULO",SÃO PAULO,111000,...,15/10/2021 13:45,15/10/2021 14:07,NaN,NaN,+00 00:22:00,SABESP,1.000000e+10,GERALDO ARGOLO BITENCOURT,Fechada,Fechada
2,215202763,,2040,HIDRÔMETRO PARADO,1056565427002,INICIATIVA ADMINISTRATIVA,MANUEL DE JESUS RODRIGUES,"RUA CORONEL JORDAO, 946, C/13 - V GUILHERME, ...",SÃO PAULO,901000,...,16/10/2021 07:46,16/10/2021 07:48,NaN,NaN,+00 00:02:00,CONSORCIO NOVA NORTE VIII,4.600043e+09,HARLEY PEREIRA VILAS BOAS,Fechada,Fechada
3,215143198,,2040,HIDRÔMETRO PARADO,232061955003,INICIATIVA ADMINISTRATIVA,JOSE NILSON FERREIRA DANTAS,"RUA MOTANGUA, 95, - V IZOLINA MAZZEI, SÃO PAULO",SÃO PAULO,204000,...,15/10/2021 15:47,15/10/2021 15:55,NaN,NaN,+00 00:08:00,CONSORCIO NOVA NORTE VIII,4.600043e+09,HARLEY PEREIRA VILAS BOAS,Fechada,Fechada
4,215158085,,2040,HIDRÔMETRO PARADO,231915705004,INICIATIVA ADMINISTRATIVA,"SR. CLIENTE, ATUALIZAR CADASTRO SR. CLIE","RUA MANUEL DE ALMEIDA, 695, - V GUILHERME, S...",SÃO PAULO,204000,...,15/10/2021 15:59,15/10/2021 15:59,NaN,NaN,+00 00:00:00,CONSORCIO NOVA NORTE VIII,4.600043e+09,HARLEY PEREIRA VILAS BOAS,Fechada,Fechada

In [67]:
# Criando um ID para deixar apenas a ultima iteracao da base (ordem-etapa):

buscaExecucaoVM['ordemTSS'] = buscaExecucaoVM['OS']+buscaExecucaoVM['TSS']

In [68]:
# Alterando o tipo de dado da coluna para data:

buscaExecucaoVM['dataFimExecucao'] = pd.to_datetime(buscaExecucaoVM['dataFimExecucao'])

In [71]:
# Deixando o dado mais recente no topo: 

buscaExecucaoVM = buscaExecucaoVM.sort_values('dataFimExecucao', ascending=True)

In [56]:
buscaExecucaoVM = buscaExecucaoVM.drop_duplicates(subset='ordemTSS', keep='last')

In [72]:
buscaExecucaoVM.head()

,OS,etapa,TSS,dsTSS,objOrigem,iniciativa,solicitante,endereco,municipio,TSE,...,dataFimExecucao,inicioPausa,fimPausa,tempoExecucao,fornecedor,contrato,equipe,statusOperacao,statusOS,ordemTSS
3055,217104821,,1060,FALTA DE ÁGUA LOCAL,723155208001,INICIATIVA CLIENTE,SUMARA CAVALCANTE ALVES,"RUA SOLDADO ANTONIO ROMANO OLIVEIRA, 34, - P...",SÃO PAULO,130000,...,2021-01-11 07:42:00,NaN,NaN,+00 00:03:00,CONSORCIO NOVA NORTE VIII,4.600043e+09,ALEXANDRE OLIVEIRA DE SOUZA,Fechada,Fechada,217105881
3185,217121564,,5610,DESOBSTRUIR RAMAL DE ESGOTO,719597501001,INICIATIVA CLIENTE,FLORIPIS PAIM DE CARMAGO,"RUA AGUAS DE XAPECO, 26, C/2 - PQ EDU CHAVES,...",SÃO PAULO,561000,...,2021-01-11 07:45:00,NaN,NaN,+00 00:15:00,TECSA SERVIÇOS LTDA.,4.600044e+09,JOSE ROCHA E SILVA FILHO,Fechada,Fechada,217127174
3176,217120835,,5610,DESOBSTRUIR RAMAL DE ESGOTO,235148253003,INICIATIVA ADMINISTRATIVA,NaN,"RUA PRINCIPAL, 201, - V MARIA, SÃO PAULO",SÃO PAULO,904600,...,2021-01-11 08:15:00,NaN,NaN,+00 00:05:00,TECSA SERVIÇOS LTDA.,4.600044e+09,ALAN DA SILVA LIMA,Fechada,Fechada,217126445
3152,217126040,,6170,APROVAR MODIFICAÇÃO DE LIGAÇÃO DE AGUA,86040381808143,INICIATIVA CLIENTE,EDAILTON DOS SANTOS NASCIMENTO,"RUA TOMAS SPEERS, 481, - V MARIA, SÃO PAULO",SÃO PAULO,617300,...,2021-01-11 08:27:00,NaN,NaN,+00 00:00:00,SABESP,1.000000e+10,MAURICIO ANTUNES DE OLIVEIRA,Fechada,Fechada,217132210
3542,216610273,,4060,SUPRIMIR LIG AGUA ENCERRAMENTO CONTRATO,239642945002,INICIATIVA CLIENTE,DAIANNY BORGES DOS SANTOS,"RUA PASCOAL PAVAN, 127, C/1 - PQ EDU CHAVES, ...",SÃO PAULO,406000,...,2021-01-11 08:40:00,NaN,NaN,+00 00:10:00,CONSORCIO NOVA NORTE VIII,4.600043e+09,ANTONIO PEREIRA DOS SANTOS,Fechada,Fechada,216614333

In [58]:
from google.colab import files

buscaExecucaoVM.to_excel('buscaExecucaoVM.xlsx', index=False)
files.download('buscaExecucaoVM.xlsx')